version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    rebase-strategy: auto
    commit-message:
      prefix: "fix"
      include: scope
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: auto
    commit-message:
      prefix: "fix"
      include: scope
    schedule:
      interval: "weekly"
