name: Build PR

on:
  pull_request:

env:
  IMAGE_BASE: "ghcr.io/${{ github.repository_owner }}/github-actions-runner"

jobs:
  generate_infos:
    uses: fullstack-devops/actions/.github/workflows/generate-build-infos.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build_base:
    runs-on: ubuntu-latest
    needs: generate_infos
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build github-actions-runner:base
        uses: docker/build-push-action@v2
        with:
          context: ./images/base
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:base-pr-${{ github.event.pull_request.number }}

  build_kaniko-sidecar:
    runs-on: ubuntu-latest
    needs: generate_infos
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build github-actions-runner:kaniko-sidecar
        uses: docker/build-push-action@v2
        with:
          context: ./images/kaniko-sidecar
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:kaniko-sidecar-pr-${{ github.event.pull_request.number }}

  build_flavors:
    runs-on: ubuntu-latest
    needs: [generate_infos, build_base]
    strategy:
      matrix:
        flavor: [ansible-k8s, fullstacked]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: link child image to current pr
        run: |
          sed -i --expression "s@FROM ${{ env.IMAGE_BASE }}.*@FROM ${{ env.IMAGE_BASE }}:base-pr-${{ github.event.pull_request.number }}@g" \
          images/${{ matrix.flavor }}/Dockerfile

      - name: Build github-actions-runner:${{ matrix.flavor }}
        uses: docker/build-push-action@v2
        with:
          context: ./images/${{ matrix.flavor }}
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:${{ matrix.flavor }}-pr-${{ github.event.pull_request.number }}
