name: Build PR

on:
  pull_request:

env:
  IMAGE_BASE: "ghcr.io/${{ github.repository_owner }}/github-actions-runner"

jobs:
  generate_infos:
    uses: fullstack-devops/actions/.github/workflows/generate-build-infos.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  load_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - id: set-matrix
        working-directory: images
        run: |
          flavours=$(ls -I "base"| xargs echo | sed 's/ /,/g')
          echo "Building flavours: $flavours"
          flavours="{\"flavour\":[\"`echo "$flavours" | sed 's/,/","/g'`\"]}"
          echo "::set-output name=matrix::$flavours"

  build_base:
    runs-on: ubuntu-latest
    needs: generate_infos
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build github-actions-runner:base
        uses: docker/build-push-action@v3
        with:
          context: ./images/base
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:base-pr-${{ github.event.pull_request.number }}

  build_flavours:
    runs-on: ubuntu-latest
    needs: [generate_infos, load_matrix, build_base]
    strategy:
      matrix: ${{ fromJson(needs.load_matrix.outputs.matrix) }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: link child image to current pr
        run: |
          sed -i --expression "s@FROM ${{ env.IMAGE_BASE }}.*@FROM ${{ env.IMAGE_BASE }}:base-pr-${{ github.event.pull_request.number }}@g" \
          images/${{ matrix.flavour }}/Dockerfile

      - name: Build github-actions-runner:${{ matrix.flavour }}
        uses: docker/build-push-action@v3
        with:
          context: ./images/${{ matrix.flavour }}
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:${{ matrix.flavour }}-pr-${{ github.event.pull_request.number }}
