name: Create Release

concurrency:
  group: ci-${{ github.repository }}-release
  cancel-in-progress: false

on:
  push:
    branches:
      - "main"

env:
  IMAGE_BASE: "ghcr.io/${{ github.repository_owner }}/github-actions-runner"

jobs:
  create_release:
    uses: fullstack-devops/actions/.github/workflows/create-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build github-actions-runner:base
        uses: docker/build-push-action@v2
        with:
          context: ./images/base
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:latest
            ${{ env.IMAGE_BASE }}:latest-base
            ${{ env.IMAGE_BASE }}:${{needs.create_release.outputs.version}}-base

      - name: Build github-actions-runner:kaniko-sidecar
        uses: docker/build-push-action@v2
        with:
          context: ./images/kaniko-sidecar
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:latest-kaniko-sidecar
            ${{ env.IMAGE_BASE }}:${{needs.create_release.outputs.version}}-kaniko-sidecar

      - name: link child image to current version
        run: |
          sed -i --expression "s@FROM ${{ env.IMAGE_BASE }}.*@FROM ${{ env.IMAGE_BASE }}:${{needs.create_release.outputs.version}}-base@g" \
          images/ansible-k8s/Dockerfile \
          images/fullstacked/Dockerfile

      - name: Build github-actions-runner:ansible-k8s
        uses: docker/build-push-action@v2
        with:
          context: ./images/ansible-k8s
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:latest-ansible-k8s
            ${{ env.IMAGE_BASE }}:${{needs.create_release.outputs.version}}-ansible-k8s

      - name: Build github-actions-runner:fullstacked
        uses: docker/build-push-action@v2
        with:
          context: ./images/fullstacked
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:latest-fullstacked
            ${{ env.IMAGE_BASE }}:${{needs.create_release.outputs.version}}-fullstacked

  publish_release:
    runs-on: ubuntu-latest
    needs: [create_release, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: Publish Release
        run: awesome-ci release publish -releaseid "$ACI_RELEASE_ID"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACI_RELEASE_ID: ${{ needs.create_release.outputs.releaseid }}

      - name: update helm charts appVersion
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.HELM_REPO_TOKEN }}
          repository: ${{ env.GITHUB_REPOSITORY_OWNER }}/helm-charts
          event-type: update_chart_version
          client-payload: '{"chart": "github-actions-runner", "version": "${{ needs.create_release.outputs.version }}"}'
